services:
  - type: web
    name: backend-translator
    env: python
    runtime: python-3.10.7
    buildCommand: pip install -r requirements1.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: Backend-Translator
